#!/usr/bin/env bash

# Export all PDFs from the 'exporting' folder using the remarkable render.
# If you are getting a 'Connection refused' error, ensure that the USB
# interface is enabled in your device settings.

function get_basename() {
	current=$(basename $1)
    if [[ ! $current =~ \.pdf ]]; then
        current=${current}.pdf
	fi
	echo $current
}

docs=$(remt ls exporting)
for pdf in $docs
do
	basename=$(get_basename $pdf)
	echo Exporting $basename...
	remt export -r remarkable $pdf ~/Desktop/$basename
done

# # Generate bib markdown files in obsidian vault.
./gen_bib.py

for pdf in $docs
do
	rm ~/Desktop/$(get_basename $pdf)
done
